### ISSUE TITLE
Please consider exposing harextract.html via GitHub Pages

### ISSUE THREAD

**Issue by kachurovskiy** [JC3/harextract#23]
This will remove the need to download the file to use it.

**Comment by JC3** [comment]
This is a good idea, I will try it this week.

**Comment by JC3** [comment]
It's here: https://jc3.github.io/harextract/harextract.html

I just need to set up an easier way to access it; maybe a link at the top of the README or something.

**Comment by kachurovskiy** [comment]
Awesome, thanks a lot.

**Comment by JC3** [comment]
https://github.com/JC3/harextract/commit/f4869c6f0d8556f21cbe56f994f06b5afc83a6fe
